name: Build
on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18 LTS
        uses: actions/setup-node@v4
        with:
          node-version: "18" # Specify Node.js 18 LTS
      - name: Check if package.json and package-lock.json are in sync
        run: |
          npm install --dry-run
          git diff --exit-code package-lock.json # This fails if package-lock.json is modified
      - name: Install dependencies
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
      - name: Build with Webpack
        run: npm run build
