name: Build
on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Check if package.json and package-lock.json are in sync
        run: |
          npm install --dry-run
          git diff --exit-code package-lock.json # This fails if package-lock.json is modified
      - run: npm ci
      - name: Build with Webpack
        run: npm run build
